load("//internal:camel_case.bzl", _camel_case = "camel_case")
load("//internal:dot_case.bzl", _dot_case = "dot_case")
load("//internal:kebab_case.bzl", _kebab_case = "kebab_case")
load("//internal:lower_case.bzl", _lower_case = "lower_case")
load("//internal:no_case.bzl", _no_case = "no_case")
load("//internal:pascal_case.bzl", _path_case = "pascal_case")
load("//internal:path_case.bzl", _path_case = "path_case")
load("//internal:screaming_snake_case.bzl", _screaming_snake_case = "screaming_snake_case")
load("//internal:snake_case.bzl", _snake_case = "snake_case")

camel_case = _camel_case
dot_case = _dot_case
kebab_case = _kebab_case
lower_case = _lower_case
no_case = _no_case
pascal_case = _pascal_case
path_case = _path_case
screaming_snake_case = _screaming_snake_case
snake_case = _snake_case
